# -*- coding: utf-8 -*-
"""python_refresher_jan2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PIIAThuZ68d3poMoGVfPZaBpIl2c3X86
"""

s = 'abc'

import math

s[:0]

-3//2

3//2

3/2

-3/2

math.trunc(-3//2)



"""## Refresher for Python"""

# Print
print('Hello World')



















